import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';
import {setup,NOW,fixture,paymentFor} from './fixtures.mjs';
import {canonical,hash,hashBytes,seal,clone} from '../src/canonical.mjs';
import {contract,bazaar,profilePath,livePaymentDestination,RECIPIENT,NETWORK,USDC} from '../src/discovery.mjs';
import {EvmRail,validatePayment} from '../src/payment.mjs';
import {runtimeFromEnvironment} from '../src/runtime.mjs';
const get=(a,p)=>a.service.handle(new Request(a.service.origin+p));
function pythonVerify(bytes,pin){const d=mkdtempSync(join(tmpdir(),'disc-v-'));try{writeFileSync(join(d,'mark.json'),bytes);return spawnSync('python3',['verify/verify_mark.py',join(d,'mark.json'),'--root-pin',pin,'--allow-test'],{encoding:'utf8'});}finally{rmSync(d,{recursive:true,force:true});}}
function rpc(a,method,params={},extra={}){return a.service.handle(new Request(a.service.origin+'/mcp',{method:'POST',headers:{'content-type':'application/json','accept':'application/json, text/event-stream',...extra},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}));}

test('signed immutable carrier separates historical claim from current resolver, service and registry',async()=>{const a=await setup();try{const p=await a.purchase(),m=JSON.parse(p.bytes),d=m.payload.discovery;assert.equal(d.artifact.name,'WHP Standing Mark v1');assert.equal(d.issuer.id,'urn:sha256:'+a.f.rootPin);assert.match(d.issuer.institutional_attribution,/TEST/);assert.equal(d.capability.requirement_id,'urn:capability:machine-verifiable-standing:1');assert(d.meaning.establishes.length);assert(d.meaning.does_not_establish.length);assert.equal(d.profile.sha256,hash(m.payload.profile));assert(!('service_url' in d));const r=await a.service.handle(new Request(d.resolution.id));assert.equal(r.status,200);const resolved=await r.json(),provider=resolved.payload.provider;assert.equal(provider.id,d.capability.id);for(const url of [provider.contract.url,provider.openapi.url,provider.profile.url,provider.material_url_template.replace('{sha256}',d.verification.source_sha256),provider.registry_url_template.replace('{purchase_id}',m.payload.purchase_id)]){const r=await a.service.handle(new Request(url));assert.equal(r.status,200,url);}const v=await a.service.handle(new Request(provider.material_url_template.replace('{sha256}',d.verification.source_sha256)));assert.equal(hashBytes(await v.text()),d.verification.source_sha256);assert.equal(a.rail.settleCalls,1);}finally{await a.store.close();}});

test('independent replay rejects an issuer-signed enlargement of the discovery meaning',async()=>{const a=await setup();try{const p=await a.purchase(),m=JSON.parse(p.bytes);m.payload.discovery.meaning.establishes+=' ALL_EXTERNAL_WORLD_TRUTH';const v=pythonVerify(canonical(seal(m.protected.type,m.payload,a.f.issuer.privateKey)),a.f.rootPin);assert.equal(v.status,1,v.stdout);}finally{await a.store.close();}});

test('independent replay rejects signed extra service fields, wrong profile, invalid resolver and semantic redirection',async()=>{const a=await setup();try{const p=await a.purchase();for(const change of [d=>d.service_url='https://unrelated.invalid',d=>d.profile.sha256='00'.repeat(32),d=>d.resolution.id+='?mutable',d=>d.meaning.claim_pointer='/payload/commerce']){const m=JSON.parse(p.bytes);change(m.payload.discovery);const v=pythonVerify(canonical(seal(m.protected.type,m.payload,a.f.issuer.privateKey)),a.f.rootPin);assert.equal(v.status,1,v.stdout);}}finally{await a.store.close();}});

test('API catalog, OpenAPI, MCP declaration, indexable documentation and immutable verifier are real GET surfaces',async()=>{const a=await setup();try{for(const path of ['/.well-known/api-catalog','/v1/openapi.json','/v1/contract','/v1/verification',profilePath,'/server.json','/llms.txt','/robots.txt','/sitemap.xml','/'])assert.equal((await get(a,path)).status,200,path);const c=await get(a,'/.well-known/api-catalog');assert.match(c.headers.get('content-type'),/application\/linkset\+json/);const head=await a.service.handle(new Request(a.service.origin+'/.well-known/api-catalog',{method:'HEAD'}));assert.equal(await head.text(),'');assert.match(head.headers.get('link'),/api-catalog/);const r=await get(a,'/server.json'),j=await r.json();assert.equal(j.remotes[0].url,a.service.origin+'/mcp');assert.equal(j.remotes[0].type,'streamable-http');assert.equal(a.rail.settleCalls,0);}finally{await a.store.close();}});

test('published purchase contract specifies exact owner payment authority and complete original input schema',async()=>{const a=await setup();try{const c=contract(a.service);assert.equal(c.purchase.requirements,a.f.requirements);assert.match(c.payment.generic_client_compatibility,/not sufficient/);assert.equal(c.cold_probe.wallet_signing,false);assert.deepEqual(c.external_registrations,[]);assert.equal(c.registration_claim,'No registration is claimed by serving this contract.');assert.equal((await get(a,new URL(c.purchase.input_schema).pathname)).status,200);}finally{await a.store.close();}});

test('Bazaar metadata matches its exact linked schema without copying the customer object',async()=>{const a=await setup();const d=mkdtempSync(join(tmpdir(),'bazaar-'));try{const q=await a.start(),b=q.terms.extensions.bazaar;assert.deepEqual(Object.keys(b).sort(),['info','schema']);assert.notEqual(b.info.input.body.buyer_key,a.f.submission.buyer_key);assert.match(b.schema.properties.input.properties.body.description,/TEST/);writeFileSync(join(d,'extension.json'),JSON.stringify(b));writeFileSync(join(d,'schema.json'),readFileSync('schemas/submission.schema.json'));const py=spawnSync('python3',['-c',`import json,sys\nfrom jsonschema import Draft202012Validator\nfrom referencing import Registry,Resource\ne=json.load(open(sys.argv[1]));s=json.load(open(sys.argv[2]));url=e['schema']['properties']['input']['properties']['body']['$ref']\nr=Registry().with_resource(url,Resource.from_contents(s))\nDraft202012Validator.check_schema(e['schema']);Draft202012Validator(e['schema'],registry=r).validate(e['info'])\nprint('VALID')`,join(d,'extension.json'),join(d,'schema.json')],{encoding:'utf8'});assert.equal(py.status,0,py.stderr);assert(Buffer.byteLength(q.response.headers.get('payment-required'))<24576,'oversized payment terms header');}finally{await a.store.close();rmSync(d,{recursive:true,force:true});}});

test('real rail forwards only server-owned discovery while retaining exact original authorized payment fields',async()=>{const a=await setup();try{const q=await a.start(),p=paymentFor(q.quote),before=canonical(p),b=bazaar(a.service),seen=[];const r=new EvmRail({facilitator_url:'https://facilitator.invalid',rpc_url:'https://rpc.invalid',network:NETWORK,discovery_extensions:{bazaar:b}},{fetchImpl:async(url,opt)=>{seen.push(JSON.parse(opt.body));return new Response(JSON.stringify({isValid:true,payer:p.payload.authorization.from,success:true}),{headers:{'extension-responses':Buffer.from(JSON.stringify({bazaar:{status:'processing'}})).toString('base64')}});}});const v=await r.verify(p,p.accepted);await r.settle(p,p.accepted);assert.equal(canonical(p),before);for(const call of seen){assert.deepEqual(call.paymentPayload.extensions,{bazaar:b});const {extensions,...original}=call.paymentPayload;assert.deepEqual(original,p);assert.deepEqual(call.paymentRequirements,p.accepted);}assert.equal(v.whp_discovery_evidence.registration_claim,false);assert(v.whp_discovery_evidence.extension_responses_base64);assert.throws(()=>validatePayment({...p,extensions:{bazaar:{fake:true}}},q.quote,NOW));}finally{await a.store.close();}});

test('LIVE destination validation pins recipient, native Base USDC and EIP-712 identity separately from signing',()=>{const r={payTo:RECIPIENT,asset:USDC,network:NETWORK,extra:{name:'USD Coin',version:'2'}};livePaymentDestination(r);for(const [k,v] of [['payTo','0x'+'11'.repeat(20)],['asset','0x'+'22'.repeat(20)],['network','eip155:1']])assert.throws(()=>livePaymentDestination({...r,[k]:v}));assert.throws(()=>livePaymentDestination({...r,extra:{name:'USDC',version:'2'}}));});

test('production runtime has no fixture fallback when actual LIVE authority is absent',async()=>{await assert.rejects(()=>runtimeFromEnvironment({}),/CONFIG_WHP_ORIGIN_REQUIRED/);});

test('MCP initializes, lists exact tools and rejects cross-origin requests',async()=>{const a=await setup();try{const r=await rpc(a,'initialize',{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'independent-test',version:'1'}});const j=await r.json();assert.equal(r.status,200);assert.equal(j.result.serverInfo.name,'WHP Standing');assert.equal(j.result.protocolVersion,'2025-11-25');const tools=await(await rpc(a,'tools/list')).json();assert.equal(tools.result.tools.length,3);assert.equal((await rpc(a,'tools/list',{}, {origin:'https://unrelated.invalid'})).status,403);assert.equal(a.rail.settleCalls,0);}finally{await a.store.close();}});

test('MCP reaches the same authenticated 402 boundary and cannot invent payment authority',async()=>{const a=await setup();try{const raw=canonical(a.f.submission);const {clientProof}=await import('../src/service.mjs');const proof=clientProof(a.f.buyer.privateKey,'POST','/v1/evaluations',raw,NOW);const r=await rpc(a,'tools/call',{name:'whp_standing_evaluation',arguments:{submission_raw:raw,client_proof:proof}});const j=await r.json();assert.equal(j.result.structuredContent.http_status,402,JSON.stringify(j));assert.equal(a.rail.settleCalls,0);const bad=await rpc(a,'tools/call',{name:'whp_standing_evaluation',arguments:{submission_raw:'{}',client_proof:proof}});const failure=await bad.json();assert.equal(failure.result.structuredContent.http_status,400);assert.equal(a.rail.settleCalls,0);}finally{await a.store.close();}});

test('MCP result retrieval preserves exact paid bytes and does not settle again',async()=>{const a=await setup();try{const p=await a.purchase();const {clientProof}=await import('../src/service.mjs');const id=p.quote.payload.purchase_id,proof=clientProof(a.f.buyer.privateKey,'GET','/v1/purchases/'+id+'/result','',NOW);const j=await(await rpc(a,'tools/call',{name:'whp_standing_result',arguments:{purchase_id:id,client_proof:proof}})).json();assert.equal(j.result.structuredContent.http_status,200,JSON.stringify(j));assert.equal(j.result.structuredContent.body_bytes,p.bytes);assert.equal(a.rail.settleCalls,1);}finally{await a.store.close();}});
