import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';
import {setup,fixture,NOW,refreshTrustStatus} from './fixtures.mjs';import {canonical,parseStrict,hash,hashBytes,seal,exact,keyId,clone} from '../src/canonical.mjs';import {assertResultContract,canonicalResolution} from '../src/contract.mjs';import {validateContract} from '../src/schema-contract.mjs';import schema from '../schemas/result.schema.json' with {type:'json'};import registrySchema from '../schemas/registry.schema.json' with {type:'json'};import resolutionSchema from '../schemas/resolution.schema.json' with {type:'json'};import {resolutionDocument,contract} from '../src/discovery.mjs';import {recognizeStandingNeed,standingNeedInterface} from '../src/need.mjs';
function batchVerify(cases,pin){const d=mkdtempSync(join(tmpdir(),'public-v1-'));try{const file=join(d,'cases.json');writeFileSync(file,canonical(cases));const r=spawnSync('python3',['-c',`import importlib.util,json,sys
spec=importlib.util.spec_from_file_location('independent','verify/verify_mark.py');v=importlib.util.module_from_spec(spec);spec.loader.exec_module(v)
cases=json.load(open(sys.argv[1]));out=[]
for c in cases:
 try:v.verify_result(c,sys.argv[2],True);out.append({'accepted':True})
 except Exception as e:out.append({'accepted':False,'error':str(e)})
print(json.dumps(out))`,file,pin],{encoding:'utf8',timeout:60000,maxBuffer:4000000});assert.equal(r.status,0,r.stdout+r.stderr);return JSON.parse(r.stdout);}finally{rmSync(d,{recursive:true,force:true});}}

test('first-public v1 constructor, closed schema and standalone replay reject semantic additions together',async()=>{const a=await setup();try{const p=await a.purchase();assert.equal(p.response.status,200,p.bytes);const m=JSON.parse(p.bytes);validateContract(m,schema);assertResultContract(m.payload);const changes=[x=>x.unknown_semantics=true,x=>x.discovery.extensions={},x=>x.discovery.artifact.historical=false,x=>x.discovery.meaning.establishes+=' All external truth.',x=>x.discovery.meaning.claim_pointer='/payload/commerce',x=>x.discovery.profile.version='2.0.0',x=>x.profile.version='2.0.0',x=>x.discovery.verification.source_sha256='00'.repeat(32),x=>x.commerce.relationship='The buyer purchased objective truth.',x=>x.decision_record.checks[0].detail='Every outside claim is now known true.',x=>x.retrieval.additional_charge=true,x=>x.discovery.status.requires_fresh=false,x=>x.discovery.service_url='https://mutable.invalid',x=>x.discovery.capability.requirement_id='urn:buy:brand:only'];const cases=changes.map(change=>{const x=clone(m);change(x.payload);return seal(x.protected.type,x.payload,a.f.issuer.privateKey);});const verified=batchVerify([m,...cases],a.f.rootPin);assert.equal(verified[0].accepted,true);assert(verified.slice(1).every(x=>x.accepted===false),JSON.stringify(verified));for(const x of cases){let schemaReject=false;try{validateContract(x,schema);}catch{schemaReject=true;}let semanticReject=false;try{assertResultContract(x.payload);}catch{semanticReject=true;}assert(schemaReject||semanticReject,'Constructor did not close an altered semantic field');}}finally{await a.store.close();}});

test('lexical integers, Unicode ordering, duplicate fields and negative zero agree in JavaScript and independent Python',()=>{const raws=['{"x":1.0}','{"x":1e0}','{"x":-0}','{"x":9007199254740992}','{"x":1,"x":2}','{"x":"\\ud800"}','{"x":NaN}'];for(const raw of raws)assert.throws(()=>parseStrict(raw));const d=mkdtempSync(join(tmpdir(),'v1-json-'));try{const cases=join(d,'cases.json');writeFileSync(cases,JSON.stringify(raws));const r=spawnSync('python3',['-c',`import importlib.util,json,sys,pathlib
s=importlib.util.spec_from_file_location('v','verify/verify_mark.py');v=importlib.util.module_from_spec(s);s.loader.exec_module(v)
for i,raw in enumerate(json.load(open(sys.argv[1]))):
 p=pathlib.Path(sys.argv[1]+str(i));p.write_text(raw)
 try:v.read(p);raise AssertionError('malformed JSON accepted')
 except (ValueError,UnicodeError):pass
print(v.canonical({'😀':1,'\\ue000':2,'a':3}))`,cases],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.equal(r.stdout.trim(),canonical({'😀':1,'\ue000':2,a:3}));}finally{rmSync(d,{recursive:true,force:true});}});

test('field-name comparison cannot be confused by NUL-joined names',()=>{assert.throws(()=>exact({'a\0b':1},['a','b']));exact({a:1,b:2},['a','b']);});

test('current resolution has a closed independently inspectable schema and exact current contract digests',async()=>{const a=await setup();try{const r=resolutionDocument(a.service);validateContract(r,resolutionSchema);assert.equal(r.payload.provider.contract.sha256,hash(contract(a.service)));assert.equal(r.payload.authority.root_public_key,a.f.trustBundle.root_public_key);const x=clone(r);x.payload.provider.extensions={};assert.throws(()=>validateContract(x,resolutionSchema));}finally{await a.store.close();}});

test('DISCOVERY delegation is distinct from an issuer role and revoked discovery cannot resolve',async()=>{const a=await setup();try{const index=a.f.trustBundle.certificates.findIndex(e=>e.protected&&keyId(e.payload.public_key)===a.service.keyId);const c=clone(a.f.trustBundle.certificates[index].payload);c.roles=c.roles.filter(r=>r!=='DISCOVERY');a.f.trustBundle.certificates[index]=seal('WHP-AUTHORITY-CERTIFICATE-v1',c,a.f.root.privateKey);refreshTrustStatus(a.f);assert.throws(()=>resolutionDocument(a.service),/DISCOVERY_AUTHORITY_REQUIRED/);}finally{await a.store.close();}const b=await setup();try{b.f.trustBundle.revocations.push(seal('WHP-KEY-REVOCATION-v1',{key_id:b.service.keyId,effective_at:NOW,reason:'TEST revocation'},b.f.root.privateKey));refreshTrustStatus(b.f);assert.throws(()=>resolutionDocument(b.service),/DISCOVERY_AUTHORITY_INVALID/);}finally{await b.store.close();}});

test('resolution mapping revision cannot silently change, roll back, or omit its predecessor',async()=>{const a=await setup();try{const r=resolutionDocument(a.service);a.service.origin='https://moved.test.invalid';assert.throws(()=>resolutionDocument(a.service),/RESOLUTION_SEQUENCE_REQUIRED_FOR_CHANGE/);a.service.resolutionSequence=1;assert.throws(()=>resolutionDocument(a.service),/RESOLUTION_PREDECESSOR_REQUIRED/);a.service.resolutionPreviousHash=hash(r.payload.provider);const moved=resolutionDocument(a.service);assert.equal(moved.payload.provider.service_origin,a.service.origin);a.service.resolutionSequence=0;a.service.resolutionPreviousHash=null;assert.throws(()=>resolutionDocument(a.service),/RESOLUTION_ROLLBACK/);}finally{await a.store.close();}});

test('canonical resolution reference rejects credentials, fragments, query mutations, noncanonical ports and path changes',()=>{for(const url of ['https://user@domain.invalid/.well-known/standing-resolution.json','https://domain.invalid/.well-known/standing-resolution.json?now','https://domain.invalid/.well-known/standing-resolution.json#now','https://DOMAIN.invalid/.well-known/standing-resolution.json','https://domain.invalid:443/.well-known/standing-resolution.json','https://domain.invalid/other','http://domain.invalid/.well-known/standing-resolution.json'])assert.throws(()=>canonicalResolution(url,'TEST'));assert.equal(canonicalResolution('https://domain.invalid/.well-known/standing-resolution.json','LIVE'),'https://domain.invalid/.well-known/standing-resolution.json');});

test('historical validation remains offline and cannot imply current status',async()=>{const a=await setup();try{const p=await a.purchase(),m=JSON.parse(p.bytes);const result=batchVerify([m],a.f.rootPin);assert.equal(result[0].accepted,true);const d=mkdtempSync(join(tmpdir(),'v1-offline-'));try{const f=join(d,'mark.json');writeFileSync(f,p.bytes);const r=spawnSync('python3',['verify/verify_mark.py',f,'--root-pin',a.f.rootPin,'--allow-test','--at',String(NOW)],{encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);const report=JSON.parse(r.stdout);assert.equal(report.current_standing,'NOT_CHECKED');assert.equal(report.live_completion_verified,false);}finally{rmSync(d,{recursive:true,force:true});}}finally{await a.store.close();}});

test('root pinning still rejects a different issuer root after first-public transition',async()=>{const a=await setup();try{const p=await a.purchase(),m=JSON.parse(p.bytes);const r=batchVerify([m],fixture().rootPin);assert.equal(r[0].accepted,false);assert.match(r[0].error,/UNTRUSTED_ROOT/);}finally{await a.store.close();}});

test('registry cannot acquire semantic extensions outside its event and authority commitments',async()=>{const a=await setup();try{const p=await a.purchase(),id=p.quote.payload.purchase_id,r=await a.service.handle(new Request(a.service.origin+'/v1/registry/'+id));const v=await r.json();validateContract(v,registrySchema);v.payload.current_meaning='Now all claims are true';assert.throws(()=>validateContract(v,registrySchema));}finally{await a.store.close();}});

test('neutral standing need does not treat self-asserted verification flags as established authority or standing',()=>{const object={standing_evidence:{independently_verifiable:true,authority_established:true,provenance_sufficient:true,qualifications_preserved:true,transformation_warrant_established:true,blocking_unknowns:false}};const r=recognizeStandingNeed(object,{operation:'EXECUTE'});assert.equal(r.result,'INDEPENDENTLY_VERIFIABLE_WARRANT_REQUIRED');assert.equal(r.capability_required.id,standingNeedInterface().capability.id);assert(!/WHP|Wheeler|Hubbell/.test(JSON.stringify(r)));assert.equal(recognizeStandingNeed({},{operation:'INFORM'}).result,'NO_STANDING_EVIDENCE');});

test('exact independent verifier and issuance profile bytes are content-addressed and retained',()=>{const manifest=JSON.parse(readFileSync('public/verifier-manifest.json'));const source=readFileSync('verify/verify_mark.py');assert.equal(hashBytes(source),manifest.sha256);assert.deepEqual(readFileSync('public/immutable/'+manifest.sha256+'.py'),source);assert.deepEqual(readFileSync('public'+manifest.path),source);assert.equal(hashBytes(readFileSync('public/immutable/'+manifest.profile_sha256+'.json')),manifest.profile_sha256);});

test('candidate 83/83 execution remains development provenance rather than a second public wire format',()=>{const prior=JSON.parse(readFileSync('evidence/verification.json'));assert.equal(prior.version,'1.0.0-candidate.1');assert.deepEqual(prior.test_counts,{tests:83,pass:83,fail:0,cancelled:0,skipped:0,todo:0});const source=readFileSync('verify/verify_mark.py','utf8');assert(!source.includes("optional=['discovery']"));assert.equal(schema.$defs.result_payload.additionalProperties,false);assert(schema.$defs.result_payload.required.includes('discovery'));});
