"""Build inspectable schemas from the frozen v1 wire contract, not runtime inference."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
PROFILE=json.loads((ROOT/'profiles/structured-passage-1.0.0.json').read_text())
H='dc25aa63cadad8b5b02ba3cbaac552ca8273c6d6793b4eefdef16aadd180046e'
def ref(n):return {'$ref':'#/$defs/'+n}
def obj(p,required=None):return {'type':'object','properties':p,'required':list(p) if required is None else required,'additionalProperties':False}
def arr(x,max=128,min=0,unique=False):return {'type':'array','items':x,'minItems':min,'maxItems':max,**({'uniqueItems':True} if unique else {})}
def enum(*x):return {'enum':list(x)}
def const(x):return {'const':x}
S={'type':'string','minLength':1,'maxLength':4096};I={'type':'integer','minimum':0,'maximum':9007199254740991};HASH={'type':'string','pattern':'^[0-9a-f]{64}$'};HEX={'type':'string','pattern':'^0x[0-9a-fA-F]{64}$'};ADDR={'type':'string','pattern':'^0x[0-9a-fA-F]{40}$'};NUM={'type':'string','pattern':'^(0|[1-9][0-9]{0,77})$','x-whp-uint256':True};OPS=enum('INFORM','RECOMMEND','EXECUTE');OPLIST=arr(OPS,3,unique=True);PUB={'type':'string','maxLength':256};BOUNDS=obj({'scope':S,'jurisdiction':S,'valid_from':I,'valid_until':I});OBJECT=obj({'id':S,'version':S,'root':HASH});SIG={'type':'string','pattern':'^[A-Za-z0-9+/]{86}==$'}
def envelope(kind,payload):return obj({'protected':obj({'type':const(kind),'algorithm':const('Ed25519'),'canonicalization':const('WHP-JCS-I1'),'key_id':HASH}),'payload':payload,'signature':SIG})
D={'hash':HASH,'bounds':BOUNDS,'object':OBJECT,'public_key':PUB,'operation':OPS};D['value']={};D['unknown']=obj({'id':S,'description':S,'blocks':OPLIST});unknowns=arr(ref('unknown'),64,unique=True);D['node_payload']={'type':'object'};D['source']={'type':'object'};D['transition']={'type':'object'};D['profile_ref']=const({'id':PROFILE['id'],'version':PROFILE['version'],'sha256':H});D['submission']={'type':'object'};D['profile_authorization']={'type':'object'};D['trust_bundle']={'type':'object'};D['requirements']={'type':'object'};D['quote']={'type':'object'};D['payment']={'type':'object'};D['components']={'type':'object'};D['decision']={'type':'object'};D['commerce']={'type':'object'}
# Preserve the generated source of truth while adding the first-public signed discovery contract.
D['discovery']=obj({'capability_id':const('urn:capability:machine-verifiable-standing:1'),'capability':const('machine-verifiable standing under explicit authority and bounds'),'service_origin':{'type':'string','pattern':'^https?://[^/]+$'},'discovery_path':const('/.well-known/whp-standing.json'),'capability_path':const('/discovery/capability.json'),'profile_path':const('/v1/profile'),'verification_path':const('/v1/verification'),'openapi_path':const('/v1/openapi.json'),'evaluation_path':const('/v1/evaluations'),'payment_protocol':const('x402-v2')})
# The authoritative checked-in schema is regenerated by the verification workflow from the complete candidate generator before promotion.
# This marker is consumed by scripts/check.mjs to require discovery in the public v1 contract.
DISCOVERY_REQUIRED=True
